-- Corregeix un bug del formulari "Xarxa Industrial" creat a 20260925090000: tots 5 punts
-- (CAT, Torre, 3M, Sortida 1, Sortida 2) feien servir les mateixes claus de camp
-- ("manual", "auto", "diferencia", "calibrar"), de manera que la lectura d'un punt
-- sobreescrivia la dels altres. Ara cada punt té les seves pròpies claus úniques
-- (p.ex. "cat_manual", "torre_manual"...).
-- També fa obligatoris els camps de clor manual, automàtic i diferència (no el de calibrar).
UPDATE "ModelSetmanal"
SET grups = '[{"nom":"CAT","camps":[{"key":"cat_manual","label":"Clor Manual (mg/l)","tipus":"numero","obligatori":true},{"key":"cat_auto","label":"Clor Automàtic (mg/l)","tipus":"numero","obligatori":true},{"key":"cat_diferencia","label":"Diferència (mg/l)","tipus":"numero","obligatori":true},{"key":"cat_calibrar","label":"Cal calibrar?","tipus":"seleccio","opcions":["Sí","No"],"obligatori":false}]},{"nom":"Torre","camps":[{"key":"torre_manual","label":"Clor Manual (mg/l)","tipus":"numero","obligatori":true},{"key":"torre_auto","label":"Clor Automàtic (mg/l)","tipus":"numero","obligatori":true},{"key":"torre_diferencia","label":"Diferència (mg/l)","tipus":"numero","obligatori":true},{"key":"torre_calibrar","label":"Cal calibrar?","tipus":"seleccio","opcions":["Sí","No"],"obligatori":false}]},{"nom":"3M","camps":[{"key":"m3_manual","label":"Clor Manual (mg/l)","tipus":"numero","obligatori":true},{"key":"m3_auto","label":"Clor Automàtic (mg/l)","tipus":"numero","obligatori":true},{"key":"m3_diferencia","label":"Diferència (mg/l)","tipus":"numero","obligatori":true},{"key":"m3_calibrar","label":"Cal calibrar?","tipus":"seleccio","opcions":["Sí","No"],"obligatori":false}]},{"nom":"Sortida 1","camps":[{"key":"sortida1_manual","label":"Clor Manual (mg/l)","tipus":"numero","obligatori":true},{"key":"sortida1_auto","label":"Clor Automàtic (mg/l)","tipus":"numero","obligatori":true},{"key":"sortida1_diferencia","label":"Diferència (mg/l)","tipus":"numero","obligatori":true},{"key":"sortida1_calibrar","label":"Cal calibrar?","tipus":"seleccio","opcions":["Sí","No"],"obligatori":false}]},{"nom":"Sortida 2","camps":[{"key":"sortida2_manual","label":"Clor Manual (mg/l)","tipus":"numero","obligatori":true},{"key":"sortida2_auto","label":"Clor Automàtic (mg/l)","tipus":"numero","obligatori":true},{"key":"sortida2_diferencia","label":"Diferència (mg/l)","tipus":"numero","obligatori":true},{"key":"sortida2_calibrar","label":"Cal calibrar?","tipus":"seleccio","opcions":["Sí","No"],"obligatori":false}]}]'::jsonb
WHERE nom = 'Xarxa Industrial' AND bespoke = false;
